name: Build macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install LatAnalyze dependencies
      run: brew install automake autoconf libtool bison flex
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.2.1
    - name: Build LatAnalyze & dependencies
      run: ./update-latan.sh
