name: Build Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive
        cd dependencies/LatAnalyze
        git rev-parse HEAD > ../.id
        cd ../..
    - name: Install basic dependencies
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install build-essential
        sudo apt install cmake bison flex python3-distutils
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1  # not v2!
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: 6.2.0
    - name: Check cache
      uses: actions/cache@v1
      with:
        path: dependencies
        key: dependencies-${{ runner.os }}-${{ hashFiles('dependencies/.id') }}
    - name: Build LatAnalyze & dependencies
      shell: bash
      run: ./update-latan.sh 4
    - name: Build Plateau
      shell: bash
      run: |
        qmake Plateau.pro -spec linux-clang CONFIG+=x86_64
        make -j4
#     - name: Deploy Plateau
#       shell: bash
#       run: |
#         macdeployqt Plateau.app -dmg -always-overwrite -verbose=2
#     - name: Upload application
#       uses: actions/upload-artifact@v1
#       with:
#         name: Plateau.dmg
#         path: Plateau.dmg
